pool:
  vmImage: ubuntu-latest

variables:
- group: SP_VALUES

steps:
- script: |
    GIT_COMMIT=$( git rev-parse --short HEAD )
    echo "##vso[task.setvariable variable=GIT_COMMIT;isOutput=true]$GIT_COMMIT"
  name: runtime_vars
  displayName: 'Set runtime variables for pipeline'

- script: |
    packer build -force sequencing.json
  displayName: 'Execute Packer script for sequencing'
  env:
    AZURE_CLOUD: $(AZURE_CLOUD)
    AZURE_SECRET: $(SP_PASSWORD)
    AZURE_CLIENTID: $(SP_CLIENTID)
    AZURE_SUBSCRIPTIONID: $(SP_SUBSCRIPTIONID)
    AZURE_TENANTID: $(SP_TENANTID)
    AZURE_LOCATION: $(AZURE_LOCATION)
    AZURE_RESOURCE_GROUP: $(AZURE_RESOURCE_GROUP)
    IMAGE_VERSION: $(runtime_vars.GIT_COMMIT)


