pool:
  vmImage: ubuntu-latest

variables:
- group: PROJECT-5058

steps:
- script: |
    packer build -force sequencing.json
  displayName: 'Execute Packer script for sequencing'
  env:
    AZURE_CLOUD: $(AZURE_CLOUD)
    AZURE_SECRET: $(sp-password-tf-5058)
    AZURE_CLIENTID: $(sp-client-id-tf-5058)
    AZURE_SUBSCRIPTIONID: $(sp-subscription-id-tf-5058)
    AZURE_TENANTID: $(sp-tenant-id-tf-5058)
    AZURE_LOCATION: $(AZURE_LOCATION)
    AZURE_RESOURCE_GROUP: $(AZURE_RESOURCE_GROUP)
